#!/usr/bin/env bash
# Bootstrap this project on the BUAS GPU server (or any ephemeral GPU container).
#
# Safe to re-run: every step is idempotent. You WILL need to re-run it after a
# container restart, because only the persistent mount survives.
#
#     ./scripts/setup_server.sh                 # runtime deps + the HTTP API
#     ./scripts/setup_server.sh --train         # plus retraining deps
#     ./scripts/setup_server.sh --persist-dir /workspace
#
# What it handles, and why each part is needed on that box:
#
#   Persistent storage   / is an overlay filesystem and is wiped on restart;
#                        /workspace is a real ext4 volume. The HF cache alone is
#                        ~15 GB (Whisper large-v3 ~3 GB, NLLB-3.3B ~6 GB), so
#                        caching to the default ~/.cache means re-downloading
#                        all of it every session.
#   apt packages         ffmpeg (stage 1 needs it) and tmux (so a dropped SSH
#                        session does not kill a 3-hour fine-tune) are not in
#                        the image and do not persist. Re-installed each run.
#   uv                   not in the image; installed into the persistent mount,
#                        so a restart needs `source /workspace/vea-env.sh`
#                        rather than a reinstall.
#   GPU selection        the box is shared: 8 cards, several already heavily
#                        allocated by other tenants. scripts/pick_free_gpu.sh
#                        picks the emptiest one and fails fast if none is free.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PERSIST_DIR="/workspace"
TRAIN=0
MIN_FREE_MIB=20000

while [[ $# -gt 0 ]]; do
    case "$1" in
        --train) TRAIN=1; shift ;;
        --persist-dir) PERSIST_DIR="${2:?--persist-dir needs a path}"; shift 2 ;;
        --min-free) MIN_FREE_MIB="${2:?--min-free needs a value in MiB}"; shift 2 ;;
        -h|--help) sed -n '2,28p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) echo "error: unknown argument '$1'" >&2; exit 2 ;;
    esac
done

say() { printf '\n=== %s ===\n' "$1"; }

# ---------------------------------------------------------------------------
say "Persistent storage"
# ---------------------------------------------------------------------------
if [[ ! -d "$PERSIST_DIR" ]]; then
    echo "error: $PERSIST_DIR does not exist. Pass --persist-dir with the mount that survives restarts (check 'df -h' for a non-overlay filesystem)." >&2
    exit 1
fi
if ! mount | grep -q " ${PERSIST_DIR} "; then
    echo "warning: $PERSIST_DIR is not a separate mount point. If it lives on the overlay filesystem it will NOT survive a restart." >&2
fi

ENV_FILE="${PERSIST_DIR}/vea-env.sh"
mkdir -p "${PERSIST_DIR}/.cache/uv" \
         "${PERSIST_DIR}/.cache/huggingface" \
         "${PERSIST_DIR}/.local/bin" \
         "${PERSIST_DIR}/vea-data" \
         "${PERSIST_DIR}/vea-models"

cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup_server.sh - source this in every new shell:
#     source ${ENV_FILE}
export PATH="${PERSIST_DIR}/.local/bin:\$PATH"
export UV_CACHE_DIR="${PERSIST_DIR}/.cache/uv"
export HF_HOME="${PERSIST_DIR}/.cache/huggingface"
export VEA_DATA_DIR="${PERSIST_DIR}/vea-data"
export VEA_MODELS_DIR="${PERSIST_DIR}/vea-models"
export VEA_DEVICE=auto
EOF
echo "wrote $ENV_FILE"
# shellcheck disable=SC1090
source "$ENV_FILE"
echo "free space on ${PERSIST_DIR}: $(df -h --output=avail "$PERSIST_DIR" | tail -1 | tr -d ' ')"

# ---------------------------------------------------------------------------
say "System packages (ephemeral - re-run after each restart)"
# ---------------------------------------------------------------------------
missing_pkgs=()
command -v ffmpeg >/dev/null 2>&1 || missing_pkgs+=(ffmpeg)
command -v tmux   >/dev/null 2>&1 || missing_pkgs+=(tmux)
if (( ${#missing_pkgs[@]} )); then
    if [[ "$(id -u)" -ne 0 ]] && ! command -v sudo >/dev/null 2>&1; then
        echo "warning: need ${missing_pkgs[*]} but you are not root and sudo is absent. Install them another way; stage 1 needs ffmpeg." >&2
    else
        SUDO=""; [[ "$(id -u)" -ne 0 ]] && SUDO="sudo"
        $SUDO apt-get update -qq
        $SUDO apt-get install -y -qq "${missing_pkgs[@]}"
        echo "installed: ${missing_pkgs[*]}"
    fi
else
    echo "ffmpeg and tmux already present"
fi

# ---------------------------------------------------------------------------
say "uv"
# ---------------------------------------------------------------------------
if command -v uv >/dev/null 2>&1; then
    echo "uv already on PATH: $(uv --version)"
else
    export UV_INSTALL_DIR="${PERSIST_DIR}/.local/bin"
    curl -LsSf https://astral.sh/uv/install.sh | sh
    # The installer may ignore UV_INSTALL_DIR depending on version; relocate.
    if ! command -v uv >/dev/null 2>&1 && [[ -x "$HOME/.local/bin/uv" ]]; then
        mv "$HOME/.local/bin/uv" "$HOME/.local/bin/uvx" "${PERSIST_DIR}/.local/bin/" 2>/dev/null || true
        hash -r
    fi
    command -v uv >/dev/null 2>&1 || { echo "error: uv install failed" >&2; exit 1; }
    echo "installed $(uv --version) into ${PERSIST_DIR}/.local/bin"
fi

# ---------------------------------------------------------------------------
say "GPU selection"
# ---------------------------------------------------------------------------
# Not exported into ENV_FILE on purpose: which GPU is free changes between
# sessions, so pinning it in a sourced file would reintroduce exactly the
# stale-index problem that the original code's hardcoded GPU 5 had. GPU 5 was
# at 47 GB of 49 GB used when this project was revived.
if gpu="$("${REPO_ROOT}/scripts/pick_free_gpu.sh" --min-free "$MIN_FREE_MIB")"; then
    export CUDA_VISIBLE_DEVICES="$gpu"
    echo "CUDA_VISIBLE_DEVICES=$gpu for this shell"
    echo "  (re-run 'export CUDA_VISIBLE_DEVICES=\$(${REPO_ROOT}/scripts/pick_free_gpu.sh)' in new shells)"
else
    echo "warning: no GPU with ${MIN_FREE_MIB} MiB free. Continuing on CPU; training will be impractical." >&2
fi

# ---------------------------------------------------------------------------
say "Python dependencies"
# ---------------------------------------------------------------------------
cd "$REPO_ROOT"
# `api` is always installed. It is fastapi and uvicorn - a few MB against the
# several GB of torch already going in - and without it `vea serve` refuses to
# start, which is now the usual way this box is driven. Leaving it out meant
# every container restart ended in the same two-step: run this script, then
# remember to re-sync with the extra it omitted.
sync_args=(--extra api)
(( TRAIN )) && sync_args+=(--extra train)
# On Linux the PyPI torch wheel already depends on the CUDA runtime
# (nvidia-cudnn-cu13, nvidia-nccl-cu13, triton), so no torch-build extra is
# needed here - plain sync gives a GPU build.
uv sync "${sync_args[@]}"

# ---------------------------------------------------------------------------
say "Verification"
# ---------------------------------------------------------------------------
uv run vea config
echo
uv run vea models || true   # exits non-zero while checkpoints are missing
echo
echo "Done. In each new shell:"
echo "  source ${ENV_FILE}"
echo "  export CUDA_VISIBLE_DEVICES=\$(${REPO_ROOT}/scripts/pick_free_gpu.sh)"
echo "Run long jobs under tmux so an SSH drop does not kill them."
